### ISSUE TITLE
Prototype integration of pyWWT and PDS Search API in Jupyter

### ISSUE THREAD

**Issue by tloubrieu-jpl** [NASA-PDS/search-api-notebook#10]
## 💡 Description

To Be completed with sub-ticket for the tasks, e.g.:
- https://github.com/NASA-PDS/search-api-notebook/issues/13
- https://github.com/NASA-PDS/search-api-notebook/issues/21
- https://github.com/NASA-PDS/search-api-notebook/issues/20

**Comment by jordanpadams** [comment]
@joaq-ram added a few sub-tasks to this for you to start on. feel free to create others and add to the Epic

**Comment by jordanpadams** [comment]
I would recommend using the `task` issue template when you create a new issue

**Comment by jordanpadams** [comment]
📆 June status: In progress. On schedule.

**Comment by jordanpadams** [comment]
📆 July status: Progress continues. Initial notebooks on schedule for first phase of intern task.
