### ISSUE TITLE
Update OREX Notebook to use PDS4 Tools to read and visualize the data

### ISSUE THREAD

**Issue by jordanpadams** [NASA-PDS/search-api-notebook#18]
### Checked for duplicates

Yes - I've already checked

### 🧑‍🔬 User Persona(s)

Data Engineer/ Data User

### 💪 Motivation

...so that I can [why do you want to do this?]

### 📖 Additional Details

Instead of using the pandas library to grab the PDS4 data and import it into a data frame, we would like to implement the PDS4_tools library instead. This would simplify the code and provide additional examples for other users in using the PDS4 tools with the data base. 

### Acceptance Criteria

**Given** a data product
**When I perform** an import of the product
**Then I expect** a working dataframe from the pds4_tools

### ⚙️ Engineering Details

will be using pds4_read() instead of pandas.read_fwf()

**Comment by joaq-ram** [comment]
Successfully implemented pds4_tools into the notebook. In addition, created another notebook that uses pandas data frames to retrieve and visualize the data in tabular form.
