### ISSUE TITLE
As a user, I want to retrieve and view IR/UV/Visual wavelength images

### ISSUE THREAD

**Issue by joaq-ram** [NASA-PDS/search-api-notebook#26]
### Checked for duplicates

No - I haven't checked

### 🧑‍🔬 User Persona(s)

Data Engineer, Data User

### 💪 Motivation

...so that I can demonstrate how to use the search API and analyze images provided a specified target, time range, wavelength,etc. 

### 📖 Additional Details

Still need to find applicable data sets for this use case. 

### Acceptance Criteria

**Given** a target and wavelength specification
**When I perform** search in PDS
**Then I expect** to view data products related to my search specifications

**Comment by tloubrieu-jpl** [comment]
@joaq-ram is looking at BepiColombo monitoring camera images and plottinh them in a notebook.

**Comment by tloubrieu-jpl** [comment]
Done with PR https://github.com/NASA-PDS/search-api-notebook/pull/28
